### PR TITLE
Update apiextensions & remove old implementation

### PR DESCRIPTION
**Pull request by MarcelMue**

### CODE REVIEW

**Comment by MarcelMue** [comment]
cc @giantswarm/team-magic Removing this stuff here as it's no longer matching the release CR we have. Revert if you think this is wrong.

**Comment by kopiczko** [comment]
Are you going to implement something different here?

**Comment by MarcelMue** [comment]
> Are you going to implement something different here?

Not currently - we mainly needed the operator to not destroy anything when the new CRD is on CPs.

**Comment by kopiczko** [comment]
I see. 👍

**Pull request merged**
