### PR TITLE
Use k8sclient collection

### PR DESCRIPTION
**Pull request by xh3b4sd**
Towards https://github.com/giantswarm/giantswarm/issues/7963.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
@kopiczko where and how can I test `release-operator`? On `gauss` there are no releases.

**Comment by kopiczko** [comment]
I see E2E are green so it's fine to merge (`e2eTestReleaseHandling` is flapping).

**Comment by xh3b4sd** [comment]
Do you have it on your list to fix the flapping? I didn't see something obviously wrong when I checked the code but this situation is really unfortunate. I was spending quite some time here.

**Comment by kopiczko** [comment]
Nothing to worry here. We'll work on it when we get back to this operator.

**Comment by kopiczko** [comment]
But this is weird that this doesn't work. Because the test itself seems to look fine.

**Pull request merged**
